__init__.py
from flask import Flask, redirect, url_for, request, render_template
from PIL import Image
import numpy as np
import base64
import re
from io import BytesIO
import os
from werkzeug import secure_filename

app = Flask(__name__, static_url_path='')
app.debug= True

@app.route("/")
def hello():
    return render_template('index.html')

@app.route('/upload', methods=['POST'])
def get_image():
    image_b64 = request.values['imageBase64']
    image_data = re.sub('^data:image/.+;base64,', '', image_b64)
    image_PIL = Image.open(BytesIO(base64.b64decode((image_data))))
    filename = request.values["filename"]
    image_PIL.save(os.path.join(app.root_path,"static/data/annotations/",filename))

    return "complete"

@app.after_request
def set_response_headers(response):
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
    return response


if __name__ == "__main__":
    app.run(host='0.0.0.0')

app.py
from flask import Flask, redirect, url_for, request, render_template, session
from PIL import Image
import numpy as np
import base64
import re
from io import BytesIO
import os
from werkzeug import secure_filename
from models.users.views import user_blueprint

app = Flask(__name__, static_url_path='')
app.debug= True

app.secret_key = "65re4g56er4"
# Registration of Blueprint path 
app.register_blueprint(user_blueprint, url_prefix="/users")

@app.route('/')
def home():
    # There is no more home for now
    # Either the user is already logged and it's showing the systems dashboard, either it asks to log
    if True:
        return render_template('users/login.html')
    else:
        return redirect(session['project'])

@app.route("/<project>")
def hello(project):
    return render_template('index.html',project = project)

@app.route('/upload', methods=['POST'])
def get_image():
    image_b64 = request.values['imageBase64']
    project = request.values['project']
    image_data = re.sub('^data:image/.+;base64,', '', image_b64)
    image_PIL = Image.open(BytesIO(base64.b64decode((image_data))))
    filename = request.values["filename"]
    image_PIL.save(os.path.join(app.root_path,"static/data/",project,"annotations",filename))

    return "complete"

@app.after_request
def set_response_headers(response):
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
    return response


if __name__ == "__main__":
    app.run(host='0.0.0.0')

models/users/views.py
from flask import Blueprint, request, session, render_template, url_for
from werkzeug.utils import redirect


user_blueprint = Blueprint('users', __name__)

@user_blueprint.route('/login', methods=['GET','POST'])
def login_user():
    if request.method == 'POST':
        password = request.form['password']
        project = request.form['project']
        if password == "happylabel":
            session['login_name'] = "guest"
            session['project'] = project
            return redirect(session['project'])
        else:
            return "wrong password"

    return render_template("users/login.html")

templates/index.html
<!DOCTYPE html>
<html>
<head>
  <title>Segmentation</title>
  <link href="../css/main.css" rel="stylesheet" type="text/css">
<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>  
<script data-main="../js/main.js" src="../js/require.js"></script>
<meta id="project" name="project" content={{project}}>
</head>
<body>
</body>
</html>

templates/users/login.html
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
		<div class="span12">
			<form class="form-horizontal" action='{{ url_for('users.login_user') }}' method="POST">
			  <fieldset>
			    <div id="legend">
			      <legend class="">Login</legend>
			    </div>
			    <div class="control-group">
			      <!-- project -->
			      <label class="control-label"  for="project">Project </label>
			      <div class="controls">
			        <input type="text" id="project" name="project" placeholder="" class="input-xlarge">
			      </div>
			    </div>
			    <div class="control-group">
			      <!-- Password-->
			      <label class="control-label" for="password">Password</label>
			      <div class="controls">
			        <input type="password" id="password" name="password" placeholder="" class="input-xlarge">
			      </div>
			    </div>
			    <div class="control-group">
			      <!-- Button -->
			      <div class="controls">
			        <button class="btn btn-success">Login</button>
			      </div>
			    </div>
			  </fieldset>
			</form>
		</div>
	</div>
</div>